apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: omucs6nuv-nodejs
  janus-idp.io/tekton: omucs6nuv-nodejs
  backstage.io/kubernetes-id: omucs6nuv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: omucs6nuv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
