apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: omucs6nuv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: omucs6nuv-nodejs 
  name: omucs6nuv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: omucs6nuv-nodejs 
